name: auto sync version

on:
  workflow_dispatch:
  schedule:
    - cron:  '0 16 * * *'
  push:
    paths:
      - '.github/workflows/auto-sync.yml'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: Get Release Version
        id: get-version
        run: |
          git fetch --tags
          export CURRENT=$(cat Dockerfile | sed -n "/controller/s/.*\/controller.\(v.*\)/\1/p")
          export LATEST=$(curl -sI https://github.com/kubernetes/ingress-nginx/releases/latest | sed -n '/tag/s/.*tag\/controller.\(v.*\)./\1/p')
          echo "current version: $CURRENT; latest release version: $LATEST"
          if [ "$LATEST" != "" ] && [ "$LATEST" != "$CURRENT" ]; then
            echo "found new release version"
            echo "::set-output name=current::$CURRENT"
            echo "::set-output name=latest::$LATEST"
          else
            echo "new release version not found"
            echo "::set-output name=latest::0"
          fi
      - name: Update Version
        if: success() && steps.get-version.outputs.latest != 0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          CURRENT: ${{ steps.get-version.outputs.current }}
          LATEST: ${{ steps.get-version.outputs.latest }}
        run: |
          echo "Update Version From $CURRENT To $LATEST"
          sed -i "s/$CURRENT/$LATEST/g" Dockerfile
          sed -i "s/$CURRENT/$LATEST/g;/$LATEST/a\  * $CURRENT" README.md
          git config user.email zhigang52110@sina.com
          git config user.name zhigang
          git commit -a -m "update version to $LATEST"
          git tag -a $LATEST -m "$LATEST"
          git push --follow-tags
