name: Release

on:
  push:
    tags:
      - "*"

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Create New Release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: ${{ github.ref }}
          body: |
            version ${{ github.ref }}
          draft: false
          prerelease: false
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        if: success()
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Push to Docker Hub
        uses: docker/build-push-action@v2
        if: success()
        env:
          LATEST: ${{ github.ref }}
        with:
          context: .
          push: true
          tags: siriuszg/nginx-ingress-controller:${{ env.LATEST }},siriuszg/nginx-ingress-controller:latest