name: release

on:
  push:
    tags:
      - "v*"

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Get Release Version
        id: get-version
        run: echo "tag=${GITHUB_REF#refs/*/}" >> "$GITHUB_OUTPUT"
      - name: Create Release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          RELEASE_VERSION: ${{ steps.get-version.outputs.tag }}
        with:
          tag_name: ${{ env.RELEASE_VERSION }}
          release_name: ${{ env.RELEASE_VERSION }}
          body: |
            version ${{ env.RELEASE_VERSION }}
          draft: false
          prerelease: false
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        if: success()
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Push to Docker Hub
        uses: docker/build-push-action@v2
        if: success()
        env:
          RELEASE_VERSION: ${{ steps.get-version.outputs.tag }}
        with:
          context: .
          push: true
          tags: siriuszg/nginx-ingress-controller:${{ env.RELEASE_VERSION }},siriuszg/nginx-ingress-controller:latest
